// Generated by the TBLips Templateengine Plug-in at Jan 23, 2020 8:45:17 PM
package com.your.app.components;

import org.treasureboat.webcore.appserver.TBContext;
import org.treasureboat.webcore.components.TBComponent;

public class Main extends TBComponent {
	
	private static final long serialVersionUID = 1L;

	public Main(TBContext context) {
		super(context);
	}
}
