// Generated by the TBLips Templateengine Plug-in at Jan 23, 2020 8:45:17 PM
package com.your.app;

import org.treasureboat.webcore.appserver.TBSession;

public class Session extends TBSession {
	
	private static final long serialVersionUID = 1L;

	public Session() {
	}
}
